blog/urls.py
from django.urls import path

from . import views 
from . feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post-list-by-tag'),
    # path('', views.PostLists.as_view(), name='post-list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post-detail'),
    path('<int:post_id>/share/', views.post_share, name='post-share'),
    path('<int:post_id>/comment/', views.post_comment, name='post-comment'),
    path('feed/', LatestPostsFeed(), name='post-feed'),
    path('search/', views.post_search, name='post-search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from blog.sitemaps import PostSiteMap

sitemaps = {
    'posts': PostSiteMap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
class Post(models.Model):

    class Status(models.TextChoices):
        #Status choices
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'


    class PublishedManager(models.Manager):
        #Query the post objects for published articles
        def get_queryset(self):
            return super().get_queryset().filter(status=Post.Status.PUBLISHED)


    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='blog_posts'
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT,
        )
    tags = TaggableManager()
    objects = models.Manager()      #Default manager
    published = PublishedManager()  #Custom manager 


    class Meta:
        ordering = ['-publish']        #Order by newest published
        indexes = [                    #Model indexing
            models.Index(fields=['-publish']),
        ]


    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse(
            "blog:post-detail", 
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
                ]
                )
    

class Comment(models.Model):

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Commented by {self.name} on {self.post}'

blog/forms.py
from django import forms 

from .models import *

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.db.models import Count
from django.contrib.postgres.search import SearchVector
from django.contrib.postgres.search import SearchQuery, SearchVector, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from taggit.models import Tag

from .models import *
from . forms import *

# Create your views here.
def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page')

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog\post\list.html', {'posts': posts, 'tag': tag})


class PostLists(ListView):
    #Alternative list view using class inheritance
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog\post\list.html'


def post_detail(request, year, month, day, post):

    post = get_object_or_404(
        Post, 
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()
    post_tags_ids = Post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    context = {'form': form, 'post': post, 'comments': comments, 'similar_posts': similar_posts}
    return render(request, 'blog\post\detail.html', context)


def post_share(request, post_id):
    #Retrieve post by id
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED,
        )
    sent = False

    form = EmailPostForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f'{cd["name"]} recommends you read {post.title}'
            message = f'Read {post.title} at {post_url}\n\n {cd["comments"]}'

            send_mail(subject, message, 'folayanjoey@gmail.com', [cd['to']])
            sent = True
        else:
            form = EmailPostForm()

    return render(request, 'blog\post\share.html', {'post': post, 
                                                    'form': form, 
                                                    'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    context = {'form': form, 'post': post, 'comment': comment}
    return render(request, 'blog\post\comment.html', context)


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')

            if len(results) == 0:
                results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query),
                ).filter(similarity__gt=0.1).order_by('-similarity')

    context = {
        'form': form,
        'query': query,
        'results': results
    }
    return render(request, 'blog\post\search.html', context)

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css\blog.css' %}">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
        <div id="sidebar">
            <h2>My Blog</h2>
            <p>This is my blog.
               I've written {% total_posts %} posts so far.
            </p>
            <p>
                <a href=" {% url 'blog:post-feed' %}">Subscribe to my RSS Feed</a>
            </p>
            <h3>Latest posts</h3>
            {% show_latest_posts 3 %}
            <h3>Most commented posts</h3>
            {% get_most_commented_posts as most_commented_posts %}
            <ui>
                {% for post in most_commented_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ui>
        </div>
        
        <script src="" async defer></script>
    </body>
</html>

blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}
{% block title %}Add a comment{% endblock title %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include 'blog\post\includes\comment_form.html' %}
    {% endif %}
{% endblock content %}

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published: {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|markdown|linebreaks }}
    <p>
        <a href="{% url 'blog:post-share' post.id %}">Share this post</a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        <p>There are no similar posts yet</p>
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} <strong>Comments</strong> {{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="'info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
            <p>There are no comments.</p>
    {% endfor %}
    {% include 'blog\post\includes\comment_form.html' %}
{% endblock content %}

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url 'blog:post-comment' post.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Add a comment"></p>
</form>

blog/templates/blog/post/latest_posts.html
<ui>
    {% for post in latest_post %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ui>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}My Blog{% endblock title %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post-list-by-tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">Published: {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|markdown|truncatewords_html:30|linebreaks }}
    {% endfor %}
    {% include 'pagination.html' with page=posts %}
    {% comment %} {{ block.super }} {% endcomment %}
{% endblock content %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}Search{% endblock title %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} results {% comment "" %}{{ total_results|pluralize }}{% endcomment %}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>There are not results for your query.</p>
        {% endfor %}
        <p><a href="{% url 'blog:post-search' %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="GET">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Search"></input>
        </form>
    {% endif %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share a post{% endblock title %}

{% block content %}
    {% if sent %}
        <h1>Email succesfully sent</h1>
        <p>
            "{{ post.title }}" was succesfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }} by email"</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock content %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>